dist: bionic

language: node_js
node_js:
  - "10"
  - "12"
  - "13"

cache:
  npm: true

script:
  - npm run lint
  - npm run test

after_script:
  - npm install snyk
  - snyk auth $SNYK_TOKEN
  - snyk test # Check node modules for vulnerability
  - snyk protect # Patch node modules (if available)
  - snyk monitor # Update dependencies to snyk

branches:
  only:
  - master # Only build master branch
  - /^greenkeeper.*$/ # Greenkeeper branches
