language: node_js
node_js:
  - "node" # latest stable Node.js release

cache:
  directories:
    - "node_modules" # cache the modules for faster build

script:
  - npm install -g snyk
  - npm install # install node modules
  - snyk auth $SNYK_TOKEN
  - snyk test # Check node modules for vulnerability

branches:
  only:
  - master # Only build master branch
  - /^greenkeeper.*$/ # Greenkeeper branches
