dist: bionic
sudo: false

language: node_js
node_js:
  - "node"

cache:
  npm: true

script:
  - npm install snyk
  - snyk auth $SNYK_TOKEN
  - snyk test # Check node modules for vulnerability
  - snyk protect # Patch node modules (if available)
  - snyk monitor # Update dependencies to snyk

branches:
  only:
  - master # Only build master branch
  - /^greenkeeper.*$/ # Greenkeeper branches
