dist: bionic

language: node_js
node_js:
  - "10"
  - "12"
  - "13"

cache:
  npm: true

script:
  - npm run lint
  - npm run test

after_script:
  - if ([[ $TRAVIS_EVENT_TYPE == "push" ]] || [[ $TRAVIS_EVENT_TYPE == "cron" ]]) && [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_NODE_VERSION == "12" ]]; then
      npm install snyk;
      snyk auth $SNYK_TOKEN;
      snyk test;
      snyk protect;
      snyk monitor;
    fi
